### ISSUE TITLE
Amount of tenants supported for this multitenant approach

### ISSUE THREAD

**Issue by MiltonLn** [tomturner/django-tenants#106]
As the title stands, i want to know how much tenants you guess (or already know based on your experience) django-tenants can handle and if you know practices that can increase this number.

I'm sorry for posting this as an issue but i didn't knew where else to post it.

Thanks.

**Comment by tomturner** [comment]
Personal I haven't tried that many this is because my SAAS project isn't live yet. I have heard people using it with hundreds 

Django Tenants uses PostgeSQL Schema which people have tested with thousands see http://stackoverflow.com/questions/14893964/how-many-schemas-can-be-created-in-postgres

However I can see issue when it come to migrating database even with parallel migrations I can see it taking hours

Hope this helps a little.

**Comment by kosz85** [comment]
Hi, from my side, we are using it as final product already. For now we have about 150 tenants, and it's number after cleaning db (we deleted inactive clients that weren't paying for a while) so it could be around hundred more. Only disadvantage is time of migrations like Tom said, as it's normal time multiplied by 150... sometimes it's about 20min, and not always running it in parallel really works because of deadlocks. Thought till now we had just 2 migrations that couldn't be run that way.
This can be speed up by squashing migrations, really everything runs much faster after that.

I don't think thousands is limit here, it's more your db, and if you would split it in shards it can support more and more schemas. The only thing would be keeping public schema slim as much possible, because then in theory schemas could exist even in different db's, at different servers.

**Comment by MiltonLn** [comment]
Thanks for your answers, i had used django tenants on an application with 63 Tenants, working fine but there is not so much concurrency, on the other hand we had used on a system with 500~ Tenants, working fine but slow when looping through tenants with connection object, the real pain was the migrations like you guys said, we started the project on Django 1.8, our migrations take at least 4 hours, i've read that on Django 1.9 the rendering models process is so fast than 1.8 so upgrading must speed up this task.

@kosz85 your 150 tenants are using the app at same time? (concurrency).

Supose we have an application that need thousands of tenants with a big ammount of information stored on each one, did you guys know about strategies that can scale (or autoscale in the best scenario) without affecting the application side (Customizing django or django-tenants)

Thank you

**Comment by kosz85** [comment]
Yes, each tenant have from 3 to 20 users, but there are few tenants with 100 users. All are used in parallel mostly at same time (working hours).
Why would you loop through tenants? That's rather ridiculous, and we never do it at request time. And in fact in celery processes we just spawn new jobs. This are rather not critical things, so we have special queue for slower tasks - but in general we have already 4 different queues (fastest, normal, slower, and very slow ;) )
If your migrations takes 4h... then smth is wrong with them. If you add 1 migration it shouldn't take more then few minutes. I thought already how to solve that, and it's possible to have almost downtime less upgrades, but after squashing migrations I just didn't need to implement it. But, you can try develop Nginx conf, that would ask django/postgres about schema version and use different uwsgi app (old for old schemas, and new for new schemas) that way migration would take same amount of time, but each tenant downtime would be only few seconds. Only constriction here are migrations of public schema, but with little tricks it can be also migrated like that.
I also use Django 1.8 and my migrations are even slower then standard ones as we are using python metaclasses, which aren't supported by Django so we use custom migration core to support them, which happen to be slower (but only for Models with multiple metaclasses). And we don't have problems with 4h migrations, the longest one was maybe near 40min. Check squashing and parallel migrations.

About scaling, you can always just scale your postgres, and it's already naturally divided on schema level so it should be really easy. In fact with good replication of public schema, you could in theory have your schemas in different postgres db's and with good made db-router it won't make any difference, as they are separated anyway. That's why I told that it's important to have only small amount of data in public schema.

**Comment by juanefren** [comment]
> Supose we have an application that need thousands of tenants with a big ammount of information stored on each one, did you guys know about strategies that can scale

We had our app working a few years before we knew about multitenancy on django, so our example may be far from optimal; we have about 200 tenants, we use one server to serve everything (webserver, app, database) for  X number of tenants depending on tenants usage, we use another app for "central management (automation tools, support tickets, announcements, and other readonly information)". We don't use django migrations, we execute SQL queries directly into each schema with which executes on every tenant of each server.

**Comment by lorinkoz** [comment]
I am wondering if publishing possible strategies for 'sharding' would fall into the scope of this project's documentation. Multi tenancy is a big thing these days and people need to know how to make the most of wonderful multi tenant approaches such like this. Thanks :)
