### ISSUE TITLE
Public tenant as separate django project

### ISSUE THREAD

**Issue by MiltonLn** [tomturner/django-tenants#123]
Hi,
On the docs says: "you can create a completely separate project for the main website." but i can't figure out how to achieve this. 

Any ideas about how to create the public tenant as a separate project?
That's because on my job we need to have the public functionality (Payments, document requests, etc) isolated from the project for security reasons (i don't know if this is really true).

**Comment by lorinkoz** [comment]
You can have a separate project that either: a) reuses the app where `TENANT_MODEL` and `DOMAIN_MODEL` are defined; or b) redefines `TENANT_MODEL` and `DOMAIN_MODEL` with `managed=False` so that only one project manages the migrations.

You can even have both codebases relatively close, since only using a different settings file can change pretty much everything.

I myself have tested the approach where the public functionality is in the same project as the shared functionality. There is a setting that comes in handy: `PUBLIC_SCHEMA_URLCONF` which lets you define a different urlconf file for the `www` site (so to say.)

There is even a way to have different user types without compromising security.
