### ISSUE TITLE
Ready for production?

### ISSUE THREAD

**Issue by lorinkoz** [tomturner/django-tenants#148]
Does anyone have experience with a massive SaaS using this project in production?
I have specific concerns with:
- Migrations with thousand tenants.
- Sharding strategies

**Comment by lorinkoz** [comment]
My company is willing to pay for some expert advise on this area.

**Comment by kosz85** [comment]
We have rather big product running, with many tenants, but still not thousands. Migrations is a pain as it take a while, that's why we added parallel migration workers to django-tenants, but not every migration is able to be run like this. We migrated to new django and python which speed things up. Our point is to have zero down time upgrades, so migration time is crucial. If product consumers would grow, next step would be serving old code and new code in parallel with migrations run in background and nginx pointing which tenant is served from which code base (old or new). But easiest way is just to avoid breaking changes in migrations or doing two or three step upgrades, where the code is not affected by migrations. Then the speed of migrations is not crucial.

Sharding would be rather easy you split your db by schemas. But we are not sharding yet, no need for it, tweaking postgres configs was enough.

**Comment by lorinkoz** [comment]
@kosz85 We are hoping to deploy in AWS. Could you provide some hours of paid consultation regarding more detailed steps in the solutions you propose? Thanks!

**Comment by tomturner** [comment]
@lorinkoz I have some experience with AWS. You can spend a lot of time going nowhere with AWS. I have deployed with Docker and AWS and native AWS. My projects haven't got many tenants yet.

**Comment by lorinkoz** [comment]
@tomturner @kosz85 Please reach me at lorinkoz at gmail so we can discuss this further. Thanks!

**Comment by tomturner** [comment]
If you want to contact me my email address is public on github
