### ISSUE TITLE
use `PUBLIC_SCHEMA_URLCONF` with no object for the default tenant

### ISSUE THREAD

**Issue by riconnon** [tomturner/django-tenants#181]
I'd like to achieve the following setup:
When a user goes to `www.<domain>` they use the `PUBLIC_SCHEMA_URLCONF` and `request.tenant` is `None`
When a user goes to `<valid_tenant>.<domain>` they use the default urlconf and `request.tenant` is set.
When a user goes to `<invalid_tenant>.<domain>` the user gets 404 or dissallowed domain response.

As far as I can tell this currently doesn't work because
https://github.com/tomturner/django-tenants/blob/master/django_tenants/middleware/main.py#L37
will result in raising the `TENANT_NOT_FOUND_EXCEPTION`

Is there interest in supporting this use-case? I'm open to writing/extending a middleware to support this.

**Comment by kosz85** [comment]
For me there is nothing to extend/support, anyone can overwrite this middleware and extend it as they want.

What you want to do is not that much of change, and maybe also not so good.
1. public schema has tenant object, and just because of that can have own configuration at model level. Also this approach is similar to `AnonymusUser`, it's better to have an object there, then check if it's not None everywhere, and fallback to some strange configurations just for public schema.
2. The other one, works like this now. 
3. The third one too. Line 11 of the file you cite: `TENANT_NOT_FOUND_EXCEPTION = Http404` , so yes when user goes to invalid page you get 404.

And I will repeat, anyone can get this middleware and rewrite it for their needs, mine looks totally different :) As I support domain.com/<tenant_name>/<url_path>/. But I don't see any need to change the default one. It's elastic and clear.

**Comment by hygull** [comment]
@kosz85 , I am okay with what you told. Can you give me any advice/links/references to read about doing the proper settings?

My requirement is the same as what @riconnon has. I am able to separate the tenants and they are isolated.

The problem is I want few of my apps to be accessed from the main domain `www.<domain>`.

**Comment by tomturner** [comment]
Make your own middleware
