### ISSUE TITLE
Q: Why is schema_name unique?

### ISSUE THREAD

**Issue by jacopsd** [tomturner/django-tenants#182]
In the source code we can find (models.py):

`schema_name = models.CharField(max_length=63, unique=True, validators=[_check_schema_name])`

Is there a particular reason why schema_name needs to be unique?
I would like to have the possibility to use the same schema for several domain_urls

**Comment by tomturner** [comment]
If you want to do this override the model and make your version non Unique. I think they should be unique so I will not be changing it.

**Comment by jacopsd** [comment]
Understood, I was not asking you to change it, just asking if you knew a good reason why it is unique. Thx.

**Comment by kosz85** [comment]
That's pretty good reason, how can you check uniqueness other way?

**Comment by jacopsd** [comment]
You don't need to check uniqueness of schema_name as there is no reason multiple domain URLs could not use the same schema. That's the whole point of my question.

**Comment by kosz85** [comment]
I see it in the opposite way, there is need to check uniqueness of `schema_name`, and there is no constriction to have only 1 domain for tenant. Did you checked `DomainMixin`? There is FK to tenant, so you have relation many domains to one tenant.
Tenant is representing schema, multiple tenants pointing to one schema is just wrong. You will have multiple migrations attempts (it's iterating tenants), multiple (different) settings per one schema? When you will be doing background tasks, you will iterate this tenants multiple times? Sorry this is just wrong concept for me. Maybe your problem is different, and it's ok there, but think about it twice.

I agree with Tom, this shouldn't be changed. Tix is closed.

**Comment by tomturner** [comment]
With a software as a service (SAAS). Each tenant / schema would have a different url. Yes you can have 2 url point to the same tenant that’s the idea of the domain model
