### ISSUE TITLE
media files on aws s3

### ISSUE THREAD

**Issue by ImplicitCoder** [tomturner/django-tenants#242]
Hi,
Any ideas on how to combine django-tenants with s3boto3 storage?
It would be nice to have a separate bucket or subdirectory on AWS s3 for each tenant.

Thanks for all your suggestions!
Joris

**Comment by ImplicitCoder** [comment]
If I override the bucket name  in django-storage's S3Boto3Storage backend like so:
     
    class TenantS3Boto3Storage(S3Boto3Storage):
        """
         Implementation that extends core Django's FileSystemStorage for multi-tenant setups.
        """
        bucket_name = utils.parse_tenant_config_path('%s')
   
        auto_create_bucket = True
        default_acl = 'public-read'
        bucket_acl = default_acl

I just get 'public' as the output of utils.parse_tenant_config_path('%s')

Any ideas more than welcome!

**Comment by b1tst0rm** [comment]
Hey @ImplicitCoder I know this is a really late response but I ran into the same problem and came up with the following solution:

The issue here is that in my case `location`  (in your case `bucket_name`) is naturally a cached property, and as such is not being updated as the schema is updated (as we expected it would be). All that needs to be done is overriding `location` to become a "property" and not a "cached property".

Here's what my backend looks like...note that I am using location and not bucket_name, but it should work the same for bucket_name. In `settings.py` just set `DEFAULT_FILE_STORAGE` to your new storage backend and this should hopefully solve your issue!

```python
from django.conf import settings
from storages.backends.s3boto3 import S3Boto3Storage
from django_tenants.utils import parse_tenant_config_path


class PrivateMediaStorage(S3Boto3Storage):
    default_acl = 'private'
    file_overwrite = False
    custom_domain = False

    @property  # not cached like in parent of S3Boto3Storage class
    def location(self):
        _location = utils.parse_tenant_config_path(
            settings.AWS_PRIVATE_MEDIA_LOCATION) # here you can just put '%s'
        return _location
```

**ALSO**...you might already be aware, and you can just ignore this advice if you want, but I am personally splitting my tenant's data into separate directories within a single bucket (hence the use of `location` over `bucket_name`). AWS by default limits you to 100 buckets. Just thought I'd let you know if you didn't already realize this :)

**Comment by svb0866** [comment]
Thanks @b1tst0rm

**Comment by ImplicitCoder** [comment]
Hi @b1tst0rm, I have to admit you're comment passed unnoticed during the summer holidays. So sorry for not answering earlier.

Thanks to @svb0866 's comment, your message just got to my attention.

So a late thank you for your helpful comment, especially the info about  the AWS bucket limit, which I was unaware of.

Unsurprisingly, I came up with a very similar solution as you suggested. For extra reference for people who encounter the same problem, more specifically in combination with django_filer, let me write down what I did:

I created a util function and passed it to my storage settings, which, in my case were used by the divio/django_filer application, that I used for my uploads like so (in settings.py):

```
FILER_STORAGES = {
    'public' : {
        'main' : {
            'UPLOAD_TO': 'tenantprefix.utils.prefixed_randomized',
        },
    },
}
```

I added tenantprefix tenantapps TENANT_APPS and add in  ` tenantprefix/utils.py `:

```
import os          
from django_tenants import utils                                                                                                                                                                                                              
from filer.utils.generate_filename import randomized                                                                                                                                                                                          

def prefixed_randomized(instance, filename):                                                                                                                                                                                                  
                                                                                                                                                                                                                                    
    prefix = utils.parse_tenant_config_path('%s') +'/'                                                                                                                                                                                        
    suffix =  randomized(instance, filename)                                                                                                                                                                                                  
    fullpath = os.path.join(prefix, suffix)  
    return fullpath                         
```

**Comment by vesaalexandru95** [comment]
@ImplicitCoder  can you post some gist with whole solution? I'm struggling with creating a media file for every tenant. Thanks a lot !

**Comment by bonfimjustino7** [comment]
For anyone looking for a current solution:
Version: django-storages-1.13.2
Cloud: AWS S3

My storage file:
![image](https://user-images.githubusercontent.com/47996966/226948165-ef93a9da-d84a-40bc-b71c-e99bd7e4e0a6.png)

my settings.py

![image](https://user-images.githubusercontent.com/47996966/226948334-9cc68a50-9e9c-4be0-8035-648448bbd35a.png)

Prefer not to create a bucket for each tenant, but within the selected bucket, the django storage lib creates a folder for each tenant.

**Comment by JayDarji** [comment]
@bonfimjustino7 Thanks for this solution.

But I'm facing a problem while using your solution.

After running application with this solution, if first media uploaded is from public schema, then every image uploaded from any schema, is being stored at public schema only.

Is there any quick idea do you have of this issue?

**Comment by bonfimjustino7** [comment]
Hello @JayDarji I recently needed to change my Storage class, it seems that in some cases just changing the location is not enough. However, with this configuration I have no problems.


```python
from django_tenants.utils import parse_tenant_config_path
from storages.backends.s3boto3 import S3Boto3Storage
from storages.utils import setting

from customers.utils import get_tenant


class TenantS3Boto3Storage(S3Boto3Storage):
    """
    Implementation that extends S3Boto3 for multi-tenant setups.
    """
    
    def url(self, name, parameters=None, expire=None, http_method=None):
        self.location = get_tenant().schema_name        
        return super().url(name, parameters, expire, http_method)
        
    def _open(self, name, mode='rb'):
        self.location = get_tenant().schema_name
        return super()._open(name, mode)
        
    def _save(self, name, content):
        # Adicione o schema do tenant ao location do arquivo antes de salvá-lo no S3
        self.location = get_tenant().schema_name        
        return super()._save(name, content)

**Comment by JayDarji** [comment]
@bonfimjustino7 Thanks for your reply.

However, I couldn't understand the difference between 

`from django_tenants.utils import parse_tenant_config_path`
and
`from customers.utils import get_tenant`

I believe you've created custom method `get_tenant` to get tenant name, but how it is different from `parse_tenant_config_path`. Can you please explain that!
Or if you can describe `get_tenant` a bit more, that will be helpful.

**Comment by JayDarji** [comment]
Also, we are facing another issue.

We have some database models in shared tenants which also have image field to store image.
Now, when we access those models via public tenant, then image URLs are correct with prefix `public` in in start, but same model when we access from another tenant (let's say that as demo tenant), then rather than prefixing with `public`, it prefixing with `demo` as current database connection is with `demo` tenant.

With this, image URL is wrong, and we can't access the image.
One idea to resolve this is to store tenant prefix when we store image path in table itself, but do you think that is possible?

**Comment by bonfimjustino7** [comment]
Hello @JayDarji, I believe there is not that much difference between get_tenant. However, get_tenant returns if it is a public domain it returns public.

Answering your second question. For tenants that are public in s3, a folder is created for each tenant, including "public". Today I don't have this problem since the TenantS3Boto3Storage class gets the correct tenant name from the s3 bucket folder

**Comment by williank** [comment]
I'd like to insist on working with bucket for each tenant. Any ideas?
