### ISSUE TITLE
How to move data from existing (single schema) database to multitennant

### ISSUE THREAD

**Issue by esseti** [tomturner/django-tenants#247]
Is there anyone that have tips and tricks on how to migrate the data?
i've a database with all the data, i would like to use this package but i've also to move the data. most of the models have a relation owner=user, but i've no clear idea on how to write a migration that takes from the old db and moves to the table in the correct schema.

quite sure i'm not the first one that wants to add this to an existing project, anyone that can help?

**Comment by tomturner** [comment]
I personally would use a custom django management command and loop over the existing data and copy it to the new schema.

**Comment by esseti** [comment]
do you have an example? should it be a raw SQL or there may be a way to user django objects? although they will be different to some extent? 
the prev object will have a field `owner` while with multitenant the field will be gone.

**Comment by atodorov** [comment]
@tomturner - on a related note how do we backup/restore the DB contents, possibly per schema? 

So far we've been using `dumpdata` and `loaddata`, still haven't gotten around to try how they work with django-tenants.

**Comment by tomturner** [comment]
@atodorov I haven't had to backup and restore yet. I guess I would use PGAdmin

**Comment by esseti** [comment]
@atodorov why not `pg_dump`

**Comment by atodorov** [comment]
> @atodorov why not pg_dump

Because we try to limit the amount of different tools and technologies we expose to our users/documentation. For some of them Django(+Docker) presents a new technology stack with which they are unfamiliar. Being able to keep things centered around manage.py helps reduce the operational knowledge our users must gain.

I know `pg_dump` will work, on the OS level I can even go with making an LVM snapshot of the block device backing up the containers. But that doesn't solve the issue for my specific use-case.

**Comment by alexandernst** [comment]
I'd say backup is completely out of the scope of this library. Also, `dumpdata` and `loaddata` won't work for anything else than a toy database. You can't backup quite some types in a json. So I'd suggest what @esseti already said, use a proper backup tool like `pg_dump`
