### ISSUE TITLE
Selenium Tests? StaticLiveServerTestCase?

### ISSUE THREAD

**Issue by MikeSmith12222** [tomturner/django-tenants#29]
Hi guys,

I just tried to get selenium running against django-tenants and guess what? It does not work.

The problem seems to be that (when inheriting from StaticLiveServerTestCase) it will run a testserver on port:8001 and I just get a page-not-available when calling the tenants test-url.

Does anyone have a running selenium-test? If yes: how did you do it? ﻿:-)

**Comment by kosz85** [comment]
I have working Selenium Tests, what is your problem? I use `django.test.LiveServerTestCase`, then `WebDriver()` and call `self.selenium.get('%s%s' % (self.live_server_url, '/some/url/'))`.
On my setup I have vagrant server running in background so I use existing server and django is not creating test one, thought it shouldn't really be a problem. My app just can't work on django test server, that's why such setup.

**Comment by MikeSmith12222** [comment]
Hi Kosz85,

thanks for the response.

I got it working. In order to use djangos runserver you need to run the server as root and pass the liverserver option.

This is the way to do it with a simple setup
```
sudo python manage.py tests --liveserver=127.0.0.1:80
```
Have a good one! :-)
