### ISSUE TITLE
Where should my custom user app go?

### ISSUE THREAD

**Issue by epschroeder** [tomturner/django-tenants#292]
I just started a new project using django_tenants. I always use a custom user model and thought the app needed to go in the TENANT_APPS. My user model 'User' is in the app 'users'.

When I want to migrate_schemas I get the following error:

django.db.utils.ProgrammingError: relation "users_user" does not exist

Can someone help me out with this?

**Comment by darcyclark** [comment]
same error here

**Comment by darcyclark** [comment]
I managed to get past this error by changing the order of SHARED_APPS listed in settings.py. I not 100% sure, but I believe I made sure my custom user model was listed *before* the app that contained the tenants model.

**Comment by kosz85** [comment]
If changing orders SHARED_APPS works - that means your migrations has wrongly set dependencies.

The other reason it may not work, but it's only when you are adding it to TENANT_APPS is that you have some dependency in SHARED_APPS, that way it just won't work. All m2m and m2one relation model tables has to be created in TENANT_APPS migrations, as `public` is migrated without any TENANT_APP active, so there may really be no `users_user` relation (table).

**Comment by epschroeder** [comment]
Thanks for the help guys!
I will try to start from scratch tonight and hopefully it will work. 

One more question though, if my custom user app should be in TENANT_APPS where should I leave 'django.contrib.auth',? In the documentation it's in the SHARED_APPS so I was wondering if this is connected to my custom user and should therefore be in TENANT_APPS.

Thanks again.

**Comment by mcroni** [comment]
@epschroeder did you get a workaround for this issue, currently facing the same issue here

**Comment by epschroeder** [comment]
@mcroni no I didn't get a workaround for this yet. 
I started a new project from scratch but still got the same error. 
Let me know when you find a solution.

**Comment by kosz85** [comment]
People are repeating over and over the same questions and problems, because of lack understanding of django itself.

I suggest to rethink your app first. I stated it few times, it's easier with User model in SHARED_APPS, if you forcefully put it to TENANT_APPS, it's also possible, but not without your work and special customizations, that we can't help you with, as each case is different.
If your users ale authorizing by email, I suggest you to put tinny User model in public schema (shared), and put One2one UserProfile model in Tenants schema, where you will put rest of real data.

If you really have to have it in TENANT_APPS, then you are on your own. But please read what I wrote before about it's consequences:
```
All m2m and m2one relation model tables has to be created in TENANT_APPS migrations,
as public is migrated without any TENANT active, so there won't be users_user relation (table)```
And now ask yourself again where to put `django.contrib.auth`, is it related to your `User` model that is only in TENANT_APPS, or not.
You may also need to reorganize login in, as you can't login to public this way, as there won't be  User and auth without selecting tenant first.

In fact the same set ot mindset you need for every single model and relation you create. As later it may work on TENANT, and break on PUBLIC. You need to remember that PUBLIC is smth you have always active, and TENANT is just a layer you switch on/off and it's always only single layer. So your app has to work without USER model when TENANT layer is not switched on.

**Comment by epschroeder** [comment]
I guess I misunderstood your first answer @kosz85 . Sorry for that. 
I now understand what you wrote and that it does have to be in SHARED_APPS so I will try it that way.

**Comment by adnanmuttaleb** [comment]
@kosz85 probably there should be a part in the docs, to clarify the consequence of placing `django.contrib,auth` in SHARED_APPS, TENANT_APPS or in both. It is a design decision all have to make, and as you have mentioned it is a very common question, anyway very useful repo, great work thanks.

**Comment by kosz85** [comment]
@adnanmuttaleb Hi, sorry but I'm no longer actively developing this lib. Project that was based on this lib is discontinued. It still works, and there is some maintenance work but no new features. I'm not aware how django-tenants fits current version of django. I think you can write this part of documentation yourself, If you will have any problems ask, and I will try help :)
