### ISSUE TITLE
AWS EB deployment: 

### ISSUE THREAD

**Issue by ibowditch** [tomturner/django-tenants#301]
Trying to deploy a multi-tenant django app to AWS elastic beanstalk. It works at first, then starts failing health checks after a while and folds. The health check failure is with httpd/apache, with this error: [Mon Aug 26 06:41:05.236891 2019] [:error] [pid 3867] Not Found: / 
after deployment. 
I tried using PUBLIC_SCHEMA_URLCONF and that does what I expected, but the underlying apache health check still fails. Any ideas?

**Comment by wnasich** [comment]
It has been a while since the last message. For anyone facing this issue, it could be solved by extending the TenantMainMiddleware in the following way:

```python
from django_tenants.middleware.main import TenantMainMiddleware
from django_tenants.utils import get_public_schema_name, get_tenant_domain_model

class CustomTenantMiddleware(TenantMainMiddleware):

    def hostname_from_request(self, request):

        hostname = super().hostname_from_request(request)

        request_url = request.get_full_path()
        if '/check_health' in request_url:
            public_schema_name = get_public_schema_name()
            domain_model = get_tenant_domain_model()
            public_domain = domain_model.objects.filter(is_primary=True, tenant__schema_name=public_schema_name).first()
            if public_domain:
                hostname = public_domain.domain

        return hostname
```

Replace the Django tenant middleware with this one in your settings file. Update your Elastic Beanstalk configurations so the health check is performed on the `/check_health` endpoint.
