### ISSUE TITLE
admin displaying apps inconsistently 

### ISSUE THREAD

**Issue by thismatters** [tomturner/django-tenants#349]
I'm seeing some unexpected results in the django admin. Specifically I'm seeing what are strictly tenant apps showing up in the global schema, and I'm seeing what is strictly a shared app _not_ showing up in the global schema admin ("Not available for global schema").

I think this might be because I am using the verbose notation in my `SHARED_APPS` and ` TENANT_APPS`, e.g. `'polls.apps.PollsConfig'`, as proposed in [the django tutorial](https://docs.djangoproject.com/en/3.0/intro/tutorial02/#activating-models). Whenever I switch to the short notation (e.g. `'polls'`) then the tenant apps only show up in the tenant admin. This is a pretty acceptable workaround, but I wanted you to know that there is some dissonance there.

The primary issue I'm facing is that there doesn't seem to be a way to obscure a shared app from tenants. Specifically, I would like to not show my tenant model to all of my tenants. Have I overlooked a method for making a table in the shared schema private (or for global admin purposes only)?

**Comment by marcoaaguiar** [comment]
We also had inconsistencies in the django admin in our project. 
I haven't had much time to dig into it to try to find what is happening. 
In particular admin.site.register/unregister have been erratic.

**Comment by ArnWac** [comment]
> The primary issue I'm facing is that there doesn't seem to be a way to obscure a shared app from tenants. Specifically, I would like to not show my tenant model to all of my tenants.

I worked around by implementing a seperate admin site for 'public'

**Comment by marcoaaguiar** [comment]
If found out that the issue that we were having was due to having the INSTALLED_APPS like in this line:
https://github.com/tomturner/django-tenants/blob/5128d9e9d2409f3cd0b09c0bd574170ff657725d/examples/tenant_tutorial/tenant_tutorial/settings.py#L175

which was causing to the order of loaded apps to be randomize (set in python does not keep order).
We had an package that was registering in its admin.py, and we were unregistering in one of our apps. If the our app loaded first it would be registered, if the package loaded first, it would be unregistered.

I hope this helps.

**Comment by tomturner** [comment]
I had the same issue use `INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]`

**Comment by marcoaaguiar** [comment]
In our project, we are using django-configurations which have configurations classes instead a configuration file (one for production, one for development, etc).
Because the scope for list comprehension behave weirdly in a class body the code snippet that you posted won't work. The workaround was to use 
`INSTALLED_APPS = list(set(SHARED_APPS) - set(TENANT_APPS))+ TENANT_APPS  # keep the order of the TENANT_APPS`

Since the order of TENANT_APPS that mattered. I failed to find a more elegant solution, but it works

**Comment by jerinpetergeorge** [comment]
I had the same issue, I did this

```python
INSTALLED_APPS = list(dict.fromkeys(SHARED_APPS + TENANT_APPS))
```
