### ISSUE TITLE
Add all Database Introspection

### ISSUE THREAD

**Issue by tomturner** [tomturner/django-tenants#37]
At the moment there is only one routine that get is in django-tenants introspection however in postgresql version there are lots i.e.

get_indexes
get_table_description

(#257)

**Comment by bdauvergne** [comment]
I implemented all that for Django 1.7, on https://github.com/bdauvergne/django-tenant-schemas/tree/wip/schema-aware-introspection it certainly needs some update for 1.8.

**Comment by tomturner** [comment]
Thank you for that I saw that change on django tenants schemes hence I opened the ticket.

**Comment by tomturner** [comment]
I tested this without doing this change and it still worked so i don't think it needed. 

Notes to myself

```python
class SandBox(View):
    def get(self, request):
        cursor = connection.cursor()
        connection.set_schema_to_public()
        dsi = DatabaseSchemaIntrospection(connection)
        tables = dsi.get_table_list(cursor)
        description = dsi.get_indexes(cursor, tables[3].name)
        assert False, description
```

**Comment by bdauvergne** [comment]
I can assure you that without my patches some migrations do not work, I think a better test would be to apply some complex migrations

**Comment by tomturner** [comment]
I realized an hour after i closed the ticket I tested wrong.

**Comment by tomturner** [comment]
@bdauvergne any chance you can give an example of a migration that goes wrong

**Comment by callerbear** [comment]
I'll endorse the changes made by @bdauvergne. 

One example of a migration that goes wrong:  Altering the list of fields in an existing unique_together index.  The migration code uses these additional introspection methods to locate the existing unique index.  If the query selecting constraints isn't restricted to the current tenant schema, the migration logic finds a list of indexes from ALL of the tenants and subsequently throws a ValueError exception saying that it found the wrong number of constraints.

We had to make changes very similar to Benjamin's to get through our migrations; his pull request looks good to me.

**Comment by tomturner** [comment]
@callerbear So would a test be?
```

class Table1(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    age = models.PositiveSmallIntegerField()

    class Meta:
        unique_together = ("first_name", "last_name")
```

then change unique_together to

`unique_together = ("first_name", "last_name", "age")`

**Comment by callerbear** [comment]
Yes, that should do it.  Our specific real-world case was more like changing from 
	unique_together = (“first_name”, “last_name”)
to 
	unique_together = (“age”, “last_name”)

(Was working on this exact problem at midnight last night after our migration failed, resolved it by 10:30 AM, then logged in to Github to create a fork and post my changes but found that the problem had already been discussed <grin>.  Never noticed it while running on single-tenant development environments, but it immediately popped up on our QA platform with multiple tenants.)

baj

**Comment by callerbear** [comment]
Tom, just realized I may not have been clear about the test case and the failures.  

As you’ve probably guessed, the failures happen only when multiple tenant schemas each contain the same table with the same unique-together indexes.  Because the various methods in the Django postgresql backend introspection code don't limit their queries to the current schema, the migration logic is unpleasantly surprised when it finds more than one copy of the unique index (seeing the copies of the unique index for ALL similar tenants).

If the count of matching constraints is not equal to 1, the schema logic raises the ValueError exception and the migration step fails.

Thank you for looking into this!

baj

**Comment by tomturner** [comment]
@callerbear I did the test on the example project i still can't get it to fail like you had any ideas on how to create the bug,

**Comment by huebel** [comment]
Hi, just ran into the same bug while migrating. Simply adding a new field to "unique_together" raises the ValueError. As I read from the discussion, there are some patches/workarounds for this? But I can't see them in any forks?

/Peter

**Comment by kosz85** [comment]
Can you give more info? Traceback, errors, whatever more? The explanations given by @callerbear seems like he had more then 1 tenant schema active, or that he had same apps (tables) both in public and tenant schema, as there is no possibility to have the same 2 or more unique constrictions. It has to be bad path or DB schema.

**Comment by huebel** [comment]
I was just calling migrate_schemas, and got a `ValueError: Found wrong number (2) of constraints for theperfectapp_version(app_id, tag_id, version_number)` as described by others.
But I noticed I was using version 1.5.7 - I'll try upgrading to 1.5.8, as it seems to have been addressed. Sorry for the inconvenience. /Peter

**Comment by huebel** [comment]
Nope, upgrading to 1.5.8 did not fix it... Here is what we get

`Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/pdr/Documents/Projects/ThePerfectApp/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/Users/pdr/Documents/Projects/ThePerfectApp/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/pdr/Documents/Projects/ThePerfectApp/venv/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/pdr/Documents/Projects/ThePerfectApp/venv/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/Users/pdr/Documents/Projects/ThePerfectApp/venv/lib/python2.7/site-packages/tenant_schemas/management/commands/migrate_schemas.py", line 51, in handle
    self.run_migrations(tenant.schema_name, settings.TENANT_APPS)
  File "/Users/pdr/Documents/Projects/ThePerfectApp/venv/lib/python2.7/site-packages/tenant_schemas/management/commands/migrate_schemas.py", line 58, in run_migrations
    command.execute(*self.args, **self.options)
  File "/Users/pdr/Documents/Projects/ThePerfectApp/venv/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/Users/pdr/Documents/Projects/ThePerfectApp/venv/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/Users/pdr/Documents/Projects/ThePerfectApp/venv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/Users/pdr/Documents/Projects/ThePerfectApp/venv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/pdr/Documents/Projects/ThePerfectApp/venv/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/pdr/Documents/Projects/ThePerfectApp/venv/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 359, in database_forwards
    getattr(new_model._meta, self.option_name, set()),
  File "/Users/pdr/Documents/Projects/ThePerfectApp/venv/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 320, in alter_unique_together
    self._delete_composed_index(model, fields, {'unique': True}, self.sql_delete_unique)
  File "/Users/pdr/Documents/Projects/ThePerfectApp/venv/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 349, in _delete_composed_index
    ", ".join(columns),
ValueError: Found wrong number (2) of constraints for theperfectapp_version(app_id, tag_id, version_number)`

**Comment by kosz85** [comment]
On what model you have his constraints? Can you check in which schemas it's set? Check if it's at public and some tenant schema you created.

**Comment by callerbear** [comment]
Sorry I couldn't continue the conversation last March -- we were in the throes of going live.  Glad to say that the production release is working well.

In order to solve the issue for us, we had to override get_table_list, get_table_description, get_indexes, get_relations, get_constraints and get_key_columns (as well as the class attribute _get_indexes_query) in introspection.py.  For each of the queries in those methods, we had to add logic that filtered on the namespace of the element, or the table_schema where that was appropriate.

I'll compare the newest code to ours and try to build a pull request if needed. (I'm a github noob, so it will probably take some time.)

**Comment by huebel** [comment]
@callerbear That is great news. A patch would be awesome!
@kosz85 When using **psql** with
```
select
      n.nspname as "schema"
    , c.conname as "name"
from
    pg_constraint c
    left join pg_namespace n on n.oid = c.connamespace
where
    c.contype='u' and c.conname like 'theperfectapp_version_%';
```
the result is something like (i have anonymised the schema names)
```
       schema       |                          name                          
--------------------+--------------------------------------------------------
 _daXXXXX           | theperfectapp_version_app_id_tag_id_version_number_key
 _deXXXXX           | theperfectapp_version_app_id_tag_id_version_number_key
 _grXXXXX           | theperfectapp_version_app_id_tag_id_version_number_key
 _moXXXXX           | theperfectapp_version_app_id_tag_id_version_number_key
 _teXXXXX           | theperfectapp_version_app_id_tag_id_version_number_key
 _trXXXXX           | theperfectapp_version_app_id_tag_id_version_number_key
 _brXXXXX           | theperfectapp_version_app_id_40f0cb23962964d1_uniq
 _goXXXXX           | theperfectapp_version_app_id_tag_id_version_number_key
 _aaXXXXX           | theperfectapp_version_app_id_40f0cb23962964d1_uniq
 _scXXXXX           | theperfectapp_version_app_id_tag_id_version_number_key
 _siXXXXX           | theperfectapp_version_app_id_40f0cb23962964d1_uniq
 _veXXXXX           | theperfectapp_version_app_id_tag_id_version_number_key
```
I looks to me, there is only one constraint per schema, and the `Version` model is defined in an app belonging to `TENANT_APPS`.

**Comment by kosz85** [comment]
And you are sure this constriction is not in your public schema?

**Comment by huebel** [comment]
@kosz85 Quite sure - I don't think there can be a constraint when there is no table?

Also, I'd like to add, we see the constraint has two different names. This stems from the fact, that some tenants were added *after* we upgraded to Django 1.8 (the ones with hex-digits in the name of the constraint).

**Comment by callerbear** [comment]
> On May 11, 2016, at 9:41 AM, Peter Hübel <notifications@github.com> wrote:
> Also, I'd like to add, we see the constraint has two different names. This stems from the fact, that some tenants were added after we upgraded to Django 1.8 (the ones with hex-digits in the name of the constraint).
> 

The problem (at least here) occurred when we had a constraint with the same name in multiple schema.  In your example, I see lots of them:  “theperfectapp_version_app_id_tag_id_version_number_key”.  If we assume that version_app_id, tag_id, and version_number_key are the same for more than one schema, then you could be in the same state as we were.

The problem is that the introspection queries aren’t limiting the results to the current schema — they’re looking across -all- schemas.  And the logic is then surprised to find the constraint returned more than once, so it fails.

The correction is to add restrict the various queries to the current table_schema or the namespace.   There are several methods in the real postgresql/introspection.py; Tom’s code overrides one of those methods, but we found that they -all- needed to be updated.  
 
I’ve apparently been successful at creating a fork that contains our correction, but I’m having some difficulty figuring out how to make a real pull request for Tom’s master branch.  (Again, I’m a complete github noob — this is my first attempt at contributing).  I’ll keep trying for a bit longer.

baj

**Comment by huebel** [comment]
It just occurs to me, that we are using *bernardopires/django-tenant-schemas* - not this project. 
Anybody know if they are drop-in compatible?

**Comment by callerbear** [comment]
> On May 11, 2016, at 10:18 AM, Peter Hübel <notifications@github.com> wrote:
> 
> It just occurs to me, that we are using bernardopires/django-tenant-schemas - not this project. 
> Anybody know if they are drop-in compatible?
> 


They’re pretty close, but don’t know if they’re drop-in compatible.  They *are* exactly the same with regards to this introspection issue, and the same change should work for both.

baj

**Comment by kosz85** [comment]
They are not, but it should be fast and easy to change from one to other, you could write some docs about how to replace it :) If you have time of course.
Year ago it was almost drop-in compatible, but I doubt that it's still true.

**Comment by tomturner** [comment]
I was trying to get the error message with you sample version table however I still can't get it to fail. I know you are getting the error however I would like to reproduce the error before I except the pull request.

**Comment by callerbear** [comment]
Understand.  I believe that it is reproducible if you create two tenants in
the same database that differ only by their scheme name, then alter the
list of fields in an existing 'index together'.

One possibility:  since the correction here is related to overriding
methods that come from yet a different package, perhaps the reason it
cannot be reproduced has to with the version of Django 1.9.2.  One could
inspect django.db.backends.postgresql.introspection.py and see if the
various queries filter on the scheme or table namespace.

Looking at the standard Django 1.10 source tree, it doesn't look like they
are, but if you happened to be using some other build of Django, perhaps
someone has fixed it there.

baj

**Comment by tomturner** [comment]
Thanks I just got it to fail so i just checking it out

**Comment by callerbear** [comment]
Sorry for the mangled grammar in that earlier message (I was typing on a
tablet, not a keyboard). Meant to say that we're running Django 1.9.2, and
that it doesn't look like its corrected in Django 1.10 either.
Interestingly enough, the MySQL introspection logic does pay attention to
the database schema, although (of course) it's using the database name
because they don't support separate schemes within a database.

baj

**Comment by huebel** [comment]
Hi Tom, that is perfectly clear. If you look at my sample, you might notice a syntactic detail in the unique_together declaration. As I wrote, we are not using your (detached) fork, but the problem seems prevalent in both projects.

**Comment by tomturner** [comment]
The problem that i was having is that I only had data in one tenant. it will only fail if you have data in multiple tenants. It now is merged. I will do a release soon (not today) thanks @callerbear for the patch
