### ISSUE TITLE
DefaultTenantMiddleware does not raise domain_model.DoesNotExist

### ISSUE THREAD

**Issue by thenewguy** [tomturner/django-tenants#389]
The [superclass](https://github.com/tomturner/django-tenants/blob/master/django_tenants/middleware/main.py#L39) catches domain_model.DoesNotExist

Default middleware [directly queries the tenant model](https://github.com/tomturner/django-tenants/blob/master/django_tenants/middleware/default.py#L25).  If the default tenant doesn't exist, the tenant DoesNotExist exception isn't caught and you get a 500 error instead of the Disallowed Host (TENANT_NOT_FOUND_EXCEPTION) one would expect

**Comment by tomturner** [comment]
@thenewguy Have you tried using the suspicious middleware

**Comment by thenewguy** [comment]
I started there but need to have the default fallback for healthchecks before swapping dns records on deploy.  Probably going to end up needing to write a version that behaves like DefaultTenantMiddleware for hosts that match a pattern and behaves like SuspiciousTenantMiddleware for those that don't.

Would you like that worked into a subclass of DefaultTenantMiddleware if that approach is taken?

**Comment by tomturner** [comment]
You can write it as another middleware and submit that however the default should remain the same as some people are quite happy with it. I can remember a debate over this before that why there is different version of the middleware.

 Even for my project I use a custom middleware because I want 127.0.0.1 and 192.168.1.XXX to go to my dev tenant.

**Comment by thenewguy** [comment]
Okay. I will close this then since it sounds like the behavior is "expected"
