### ISSUE TITLE
"reverse" with tenant?

### ISSUE THREAD

**Issue by bartmika** [tomturner/django-tenants#87]
How do I utilize the django urlresolve **reverse** function to take into account a particular tenant subdomain in the URL? I didn't see any custom **reverse** function in https://github.com/tomturner/django-tenants/blob/master/django_tenants/urlresolvers.py

Ex:

``` python
from django.core.urlresolvers import resolve, reverse
url = reverse('tenant_dashboard')
print(url)  # Result: /en/dashboard

# The next code is the desired functionionality I am looking for
url = tenant_reverse("some_tenant_name", "tenant_dashboard")
print(url)  # Result: http://some_tenant_name.mydomain.com/en/dashboard
```

I ask this question because I noticed the `django-subdomains` library has this sort of functionality. See here: https://github.com/tkaemming/django-subdomains/blob/master/subdomains/utils.py#L41

 Thanks!

**Comment by rodolfomartinez** [comment]
+1

**Comment by bartmika** [comment]
Alright, my fix was this code:

```python
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.core.urlresolvers import resolve, reverse
from foundation_public.models.organization import PublicOrganization

# ...

def index_page(request):
    org = PublicOrganization.objects.get(owner_id=request.user.id)
    url = 'https://' if request.is_secure() else 'http://'
    url += str(org.schema_name) + '.'
    url += get_current_site(request).domain
    url += reverse('tenant_dashboard')
    print(url)  # Result: http://my_test_tenant.my_test_domain.com

# ...
```

However, I think having a custom reverse function for specific tenants would be immensely useful.

**Comment by tomturner** [comment]
I can add that in at some point. If someone create a pull request tat would be good.

**Comment by kosz85** [comment]
What a problem adding such func in your project? Everyone can do it on it's own, as not everyone is using sites ;) For example I have custom reverse so it's adding me `URL_PREFIX` which is smth like `/tenant/{{tenant.slug_name}}` so finally it's joined into smth like `/tenant/abc/some/url/in/app`, and I have many tenants per one domain. It all depends how you use this lib.

**Comment by bartmika** [comment]
Hmmm you make a good point @kosz85. What do you think we should do in this case? I think having somesort of **resolve** function per tenant to be a extremly useful function.

**Comment by kosz85** [comment]
I was thinking a bit about this issue. For me it's more like thing for examples chapter in docs (some kind of HowTo), then smth placed in core lib.
We would need to have specific implementation to be able implement `resolve` like that, so I think maybe another project that is using this one, or new module with explicit implementation of models. This lib isn't the simplest, but you know this problem itself isn't one of the simplest one :) 
But if you want to add some implementation, I suggest to add `resolve` method on `TenantMixin` and dummy one, so that later you could overwrite it when inheriting. Then what you would do is use just `tenant.resolve('some_view')` . That or another way (by domain, or url path) it's tenant related, so it can be a method of tenant. But overwriting/monkeypatching django `resolve` should stay on shoulders each developer, we can write how to do that at docs and docstrings. Especially that it's different from lib to lib, as DRF has to be mokeypatched separately.

**Comment by bartmika** [comment]
Thanks for your input @kosz85. This sounds like a great idea! I'd like to implement your suggestion. 👍
