### ISSUE TITLE
Django 1.10 support

### ISSUE THREAD

**Issue by tomturner** [tomturner/django-tenants#91]
Need to test Django 1.10.
Does it work?

**Comment by bartmika** [comment]
I tried installing ``django-tenants`` with ``django 1.10.2`` but what ends up happening is ``pip`` uninstalls django and installs ``Django-1.9.10``.

**Comment by rodolfomartinez** [comment]
+1

**Comment by tomturner** [comment]
I have uploaded a new version to pip

**Comment by bartmika** [comment]
hi @tomturner, I have ran ``django-tenants`` on ``django 1.10.2`` and I can confirm it is now working with your latest change.

I'd like to make an interesting note:

I also installed ``django-tenants-schema`` on ``django 1.10.2`` to compare the performance of ``django-tenants`` library and I am happy to say that ``django-tenants`` is a far superior library.

You can safely close this ticket; however, because of recent ``django 1.10`` changes, you will need to update the **docs**. I will create the separate tickets to address these issues.

**Comment by tomturner** [comment]
@bartmika thank you very much.
